### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by rimmesbe** [david-vieira/prj-rev-bwfs-dasmoto#6]
Grade: Satisfactory

Summary: Nice job on this project, the site looks good. You used some good techniques and kept your code well organized. Take a look at the issues I created for some best practice tips as well as some new techniques you can start using. Overall well done, you are ready for the next units.

**Comment by david-vieira** [comment]
Thank you, for your review, I completely agree with your review. Will take everything into note for improvement in my next commits
